### ISSUE TITLE
LSP-Elm unable to load since upgrade

### ISSUE THREAD

**Issue by sylbru** [sublimelsp/LSP-elm#62]
Hi,

As I understand it this might be linked to the recent upgrade to Python 3.8. My LSP-Elm install doesn’t run currently. I’ve tried restarting ST and reinstalling LSP-Elm. Haven’t tried reinstalling Sublime-LSP yet but I figured it might be good to keep it this way (not working) if we want to be able to investigate.

Basically it seems to fail because it can’t find the `typing_extensions` module, which seems to be a Python 3.8 thing?

```
Traceback (most recent call last):
  File "/opt/sublime_text/Lib/python38/sublime_plugin.py", line 325, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.8/importlib/__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 868, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/vaincil/.config/sublime-text-3/Installed Packages/LSP-elm.sublime-package/types.py", line 1, in <module>
ModuleNotFoundError: No module named 'typing_extensions'
```

* Sublime-LSP version 2.0.0
* LSP-Elm version 2.1.1
* `print(sys.version)` returns `3.8.12 (default, Dec  7 2022, 14:07:19) [Clang 15.0.6 ]`

Happy to provide more info!
Thanks.

**Comment by predragnikolic** [comment]
Thanks for the issue. 
Yes, it was an oversight from my side.

**Comment by predragnikolic** [comment]
Should be fixed with https://github.com/sublimelsp/LSP-elm/releases/tag/v2.1.3
It would take up to 2h for Package Control to pickup the release.

**Comment by sylbru** [comment]
Thanks a lot for your reactivity! It looks like I have another error now though, after upgrading:
```
Traceback (most recent call last):
  File "/opt/sublime_text/Lib/python38/sublime_plugin.py", line 325, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.8/importlib/__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 868, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/vaincil/.config/sublime-text-3/Installed Packages/LSP-elm.sublime-package/types.py", line 5, in <module>
  File "/home/vaincil/.config/sublime-text-3/Installed Packages/LSP-elm.sublime-package/types.py", line 6, in ShowReference
  File "./python3.8/typing.py", line 261, in inner
  File "./python3.8/typing.py", line 685, in __getitem__
  File "./python3.8/typing.py", line 685, in <genexpr>
  File "./python3.8/typing.py", line 149, in _type_check
TypeError: Parameters to generic types must be types. Got {}.
```

Tell me if you prefer me to open a new issue.

**Comment by predragnikolic** [comment]
This is exactly what happens when I quickly "fix" things 🙃 

> TypeError: Parameters to generic types must be types. Got {}.

This should be fixed with https://github.com/sublimelsp/LSP-elm/releases/tag/v2.1.4
My bad, again.

**Comment by sylbru** [comment]
Ha, I know the feeling! Will try this :)

**Comment by sylbru** [comment]
Works great now, thanks a lot!
